# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6589b9681a9af4f3599546d389eeadb7f14cce710d5a51f51201f99a256c45a97339f8027fd742c1448ea658df7b167c235069819379713dfc994584e9345c79

test:
  secret_key_base: bd48008f268a6a6fd94e9109a06f70b38b45e97c7e850502203bb74806d61db331f0d4cb39f6438aa8142c4e997f1168935478feb191dbc892faa3c1a78ec97b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
